## CHANGE this to the name of your plugin.
name: SF-Storage+

## CHANGE this to your username.
author: King_Jpao

## CHANGE this to a meaninful but short description of your plugin.
description: A Minecraft Slimefun Addon, Can Be Used For a Better Storage, Management Of Itens And Better SF Sistems

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.kingjpao.sfstorageplus.SFStoragePlus

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/King-Jpao/SF-StoragePlus

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
